#!/bin/bash


writeHead(){
echo "<m:buyStocks xmlns:m=\"http://services.samples/xsd\">" > $1
}

writeTail() {
    echo "</m:buyStocks>" >> $1
}

writeIBM(){
    echo "<order><symbol>IBM</symbol><buyerID>john</buyerID><price>140.34</price><volume>$2</volume></order>" >> $1
}

#################### START ###########################

iterations=$1
file_name=$1Elements_buyStocks.xml

echo "Creating file ..."

writeHead "$file_name"

loop=$iterations

while [ "$loop" !=  "0" ]
do
    writeIBM "$file_name" "$loop"
    loop=`expr $loop - 1`
done

writeTail "$file_name"

echo "File Name          : $file_name"
echo "No. of elements     : $iterations"

#################### END ###########################
